### ISSUE TITLE
Use Sylius templates events for displays

### ISSUE THREAD

**Issue by maximehuran** [Setono/SyliusMailchimpPlugin#94]
It could be nice for admin and shop to use sylius template events to do the displays without rewrite the templates.
 
- [ ] Ui Event for admin channel form
- [ ] Ui event for shop checkout complete form
- [ ] Ui event for shop address form

Example for admin channel form

```
        sylius.admin.channel.form.second_column_content:
            blocks:
                mailchimp:
                    template: '/Admin/Channel/Form/_mailchimp.html.twig'
                    priority: 9
```

And in the template

```
<div class="ui attached segment">
    {{ form_row(form.displaySubscribeToNewsletterAtCheckout) }}
</div>
```
